### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by sourpatchdad** [dreed47/redfin#14]
This integration seems to have broken today. Was working great up until now. Not sure if issue is on Redfin side or something in the project.

**Comment by davlaw** [comment]
Same here, 


Error

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by braymond1776** [comment]
Same here

**Comment by twitchnln** [comment]
Seeing the same

**Comment by gawelko** [comment]
DItto

**Comment by carealtor** [comment]
Same here

**Comment by pathofleastresistor** [comment]
For now I wrote an AppDaemon script to cover my needs until this is resolved.

https://gist.github.com/pathofleastresistor/c87e8250fc1e5b9545c99f2dc26489b6

**Comment by dreed47** [comment]
The redfin python library that we use no longer works... investigating

**Comment by dreed47** [comment]
see new release for partial fix info

**Comment by carealtor** [comment]
It is making me "ADD ENTRY".  Is there a way to keep my original entry so I don't loose all my historical data?

**Comment by dreed47** [comment]
Yeah, sorry about that, I didn't mention it but you're probably going to have to delete and re-add the properties. I had to change the way I was storing the data and its not compatible to the previous version. If I had more time to work on it I could have tried to convert them but I figured people would want a working integration sooner rather than later.
