### ISSUE TITLE
Version 1.1.6 broken with property_id error

### ISSUE THREAD

**Issue by chilicheech** [dreed47/redfin#15]
```
This error originated from a custom integration.

Logger: custom_components.redfin
Source: custom_components/redfin/__init__.py:44
integration: Redfin
First occurred: 1:53:08 PM (2 occurrences)
Last logged: 2:13:27 PM

Error setting up Redfin integration: 'property_id'
```

**Comment by dreed47** [comment]
Yeah, sorry, I didn't mention it but you're probably going to have to delete and re-add the properties.  I had to change the way I was storing the data and its not compatible to the previous version.  If I had more time I could have tried to convert them but I figured people would want a working integration sooner rather than later.

**Comment by chilicheech** [comment]
Cool, I removed and re-added and it now works. Thanks so much for fixing this 😁

**Comment by carealtor** [comment]
> Yeah, sorry, I didn't mention it but you're probably going to have to delete and re-add the properties. I had to change the way I was storing the data and its not compatible to the previous version. If I had more time I could have tried to convert them but I figured people would want a working integration sooner rather than later.

That's a bummer.  I have 3 years of tracking our home's value.  I hate to loose that.

Thanks for the fix.

**Comment by broyuken** [comment]
Long Term Statistics seem to be gone after updating. Is there a way to get them back?
